### ISSUE TITLE
gtnh-2.7.0-beta2 crush while loading

### ISSUE THREAD

**Issue by PinkYuDeer** [ElytraServers/GTNH-CutCorners#3]
### 你的整合包版本

gtnh-2.7.0-beta2

### Bug的具体细节

gregtech-api has some break change。

**Comment by PinkYuDeer** [comment]
this pull request has failed QAQ

**Comment by Taskeren** [comment]
> this pull request has failed QAQ

Any logs?

If you are talking about the GitHub actions, the failure is caused in the server testing phase, which is because the actions have time limits, and it fails before the action ends.
You can still get the artifact from that action btw.

**Comment by PinkYuDeer** [comment]
I saw it. Thank you very much.

**Comment by PinkYuDeer** [comment]
I test on my 2.7.0 beta3 server and it works perfectly, fantastic.
