### ISSUE TITLE
The mining pipe does not automatically recover.

### ISSUE THREAD

**Issue by PinkYuDeer** [ElytraServers/GTNH-CutCorners#6]
### 你的整合包版本

gtnh-2.7.0-beta3

### Bug的具体细节

When all mines are mined, it stops and turns into an error box.
![image](https://github.com/user-attachments/assets/a53e4d71-92ae-414c-9437-f5612d8f5dd0)
Server logs repeat print:[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArithmeticException

**Comment by Taskeren** [comment]
麻烦提供更多信息，包括完整日志，复现方法等

**Comment by PinkYuDeer** [comment]
新版本已经可以回收管道了，旧版本b3问题不再.
