### ISSUE TITLE
Water Purification Plant Water tier 1-8  

### ISSUE THREAD

**Issue by PinkYuDeer** [ElytraServers/GTNH-CutCorners#7]
### 你的整合包版本

gtnh-2.7.0-beta3

### 机器/配方所属的Mod

add by gergtech auther : NotAPenguin

### 需要添加的机器、配方的具体细节

make "make water progress" to 1T

**Comment by Taskeren** [comment]
It is working properly. Check out [the latest GitHub action build](https://github.com/ElytraServers/GTNH-CutCorners/actions/runs/12333648964).
